# Generated by Django 3.2.4 on 2021-07-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_items', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('topic', models.CharField(max_length=80)),
            ],
        ),
    ]
